PROMPT='%F{086}%2c%F{013} [%f '
RPROMPT='$(git_prompt_info) %F{013}] %F{086}%D{%H:%M}'

ZSH_THEME_GIT_PROMPT_PREFIX="%F{226}"
ZSH_THEME_GIT_PROMPT_SUFFIX="%f"
ZSH_THEME_GIT_PROMPT_DIRTY=" %F{197}\u276f%f"
ZSH_THEME_GIT_PROMPT_CLEAN=""
