PROMPT='%F{122}%2c%F{013} [%f '
RPROMPT='$(git_prompt_info) %F{013}] %F{122}%D{%H:%M}'

ZSH_THEME_GIT_PROMPT_PREFIX="%F{069}"
ZSH_THEME_GIT_PROMPT_SUFFIX="%f"
ZSH_THEME_GIT_PROMPT_DIRTY=" %F{203}\u276f%f"
ZSH_THEME_GIT_PROMPT_CLEAN=""
